# default build.properties

app.name=javagnupg
app.type=jar
app.version=0.1.5
app.customer=LGPL
app.vendor=freiheit.com technologies gmbh
app.year=2008-2026

lib=./lib

build.compiler=modern
compile.debug=true
compile.deprecation=false
compile.optimize=true

#where to put the source code
src=src

#where to put the generated class files
build=build

#where to put the distribution files
dist=dist

#where to put etc stuff :-)
etc=etc
